### ISSUE TITLE
Arrow functions

### ISSUE THREAD

**Issue by ocarneiro** [enjalot/tributary#132]
ES6 has a great feature called "[arrow functions](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Functions/Arrow_functions)" that simplifies writing anonymous functions.

`function (d) { return d } ` becomes `d => d`

It would be great if we could use it in Tributary.

**Comment by georules** [comment]
I'm not sure how I feel about this.  Tributary loads the code you write into the browser, showing you what the browser will render from that code.  This means the very same code with no modification would work in that same browser window.  Supporting features that the browser does not support by default means a hidden context that your code goes through before being executed - that may not be easily exportable.

**Comment by enjalot** [comment]
I would recommend using Blockbuilder as I've moved all my effort from Tributary to there. You can do this by using babel in your block as seen here:
http://blockbuilder.org/micahstubbs/4fc5b8bdb27bde8a321ba410152a31ae
